accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns= [
    path('signup/',views.signup,name='signup'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('login/',auth_views.LoginView.as_view(template_name='login.html'),name='login'),
    path('settings/change_password/',auth_views.PasswordChangeView.as_view(template_name='change_password.html'),name='change_password'),
    path('settings/change_password/done/',auth_views.PasswordChangeDoneView.as_view(template_name='change_password_done.html'),name='password_change_done'),
    
]

boards/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.home,name='home'),
    path('about/',views.about,name='about'),
    path('boards/<int:board_id>',views.board_topics,name='board_topics'),
    path('boards/<int:board_id>/new',views.new_topic,name='new_topic'),
    path('boards/<int:board_id>/topics/<int:topic_id>',views.topic_posts,name='topic_posts'),
    path('boards/<int:board_id>/topics/<int:topic_id>/reply',views.reply_topic,name='reply_topic'),
    

]

discussion_board/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    
    # boards URLs
    path('',include('boards.urls')),
    
    path('',include('accounts.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

boards/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Board(models.Model):
    name = models.CharField(max_length=50,unique=True)
    description = models.CharField(max_length=200)
    
    def __str__(self):
        return self.name
    

class Topic(models.Model):
    subject = models.CharField(max_length=250)
    board = models.ForeignKey(Board,related_name='topics',on_delete=models.CASCADE)
    created_by = models.ForeignKey(User,related_name='topics',on_delete=models.CASCADE)
    created_dt = models.DateTimeField(auto_now_add=True)
    
    
class Post(models.Model):
    message = models.TextField(max_length=4000)
    topic = models.ForeignKey(Topic,related_name='posts',on_delete=models.CASCADE)
    created_by = models.ForeignKey(User,related_name='posts',on_delete=models.CASCADE)
    created_dt = models.DateTimeField(auto_now_add=True)
    
    

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    email = forms.EmailField(
        max_length=255,
        required=True,
        widget=forms.EmailInput(attrs={
            'placeholder': 'Enter your email',
            'class': 'form-control'
        }),
        label="Email"
    )

    username = forms.CharField(
        max_length=150,
        required=True,
        widget=forms.TextInput(attrs={
            'placeholder': 'Enter your username',
            'class': 'form-control'
        }),
        label="Username"

    )
    first_name = forms.CharField(
        max_length=50,
        widget=forms.TextInput(attrs={
            'placeholder': 'Enter your first name',
            'class': 'form-control'
        }),
        label='First Name'
    )
    
    last_name = forms.CharField(
        max_length=50,
        widget=forms.TextInput(attrs={
            'placeholder': 'Enter your last name',
            'class': 'form-control'
        }),
        label='Last Name'   
    )
    
    password1 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={
            'placeholder': 'Enter your password',
            'class': 'form-control'
        }),
        label="password"

    )

    password2 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={
            'placeholder': 'Confirm your password',
            'class': 'form-control'
        }),
        label="password Confirm"
    )

    
    
    class Meta:
        model = User
        fields = ['username', 'email','first_name','last_name', 'password1', 'password2',]

boards/forms.py
from django import forms
from .models import Topic,Post

class PostForm(forms.ModelForm):
    
    class Meta:
        
        model = Post
        fields = ['message',]

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from .forms import SignUpForm
from django.contrib.auth import login as auth_login
# Create your views here.


def signup(request):
    form = SignUpForm()
    if request.method=='POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request,user)
            return redirect('home')
    
    
    return render(request,'signup.html',{'form':form})

boards/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.http import HttpResponse
from .models import Board,Topic,Post
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .forms import PostForm
# Create your views here.

def home(req):
    boards = Board.objects.all()
    return render(req,'home.html',{'boards':boards})

def board_topics(req,board_id):
    
    # board = Board.objects.get(id=board_id)
    board = get_object_or_404(Board,pk=board_id)
    return render(req,'topics.html',{'board':board})


@login_required
def new_topic(req,board_id):
    board = get_object_or_404(Board,pk=board_id)
    
    if req.method == 'POST':
        subject = req.POST['subject']
        message = req.POST['message']
        # user = User.objects.first()
        
        topic = Topic.objects.create(
            subject=subject,
            board=board,
            created_by=req.user,
        )
        
        post = Post.objects.create(
            message=message,
            topic = topic,
            created_by = req.user
        )
        
        return redirect('board_topics',board_id=board.pk)
    
    return render(req,'new_topic.html',{'board':board})


def topic_posts(req,board_id,topic_id):
    topic = get_object_or_404(Topic,board__pk=board_id,pk=topic_id)
    
    return render(req,'topic_posts.html',{'topic':topic})
    
        
@login_required
def reply_topic(req,board_id,topic_id):
    
    topic = get_object_or_404(Topic,board__pk=board_id,pk=topic_id)
    if req.method == 'POST':
        form = PostForm(req.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.topic = topic
            post.created_by = req.user
            post.save()
            return redirect('topic_posts',board_id=board_id,topic_id=topic_id)
    else:
        form = PostForm()
    return render(req,'reply_topic.html',{'topic':topic,'form':form})

def about(request):
    return HttpResponse('<h1>About</h1>')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{%static 'css/style.css'%}">
    <link rel="icon" href="{% static 'imgs/user.png' %}" type="image/png">
    <title>
        {%block title %}
            Home
        {%endblock%}
    </title>

</head>

<body class="bg-light">
    {%block body%}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">Django Boards</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav m-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">About</a>
                    </li>
                </ul>
                {%if user.is_authenticated%}
                <div class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-white fs-6 text-capitalize" href="#" id="navbarDropdown"
                        role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Welcome {{user.username}}
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#">My Account</a></li>
                        <li><a class="dropdown-item" href="{% url 'change_password'%}">Change Password</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <form method="post" action="{% url 'logout' %}" style="display: inline;">
                                {% csrf_token %}
                                <button type="submit" class="dropdown-item">Log out</button>
                            </form>
                        </li>
                    </ul>
                </div>
                {%else%}
                <a href="{% url 'login'%}" class=" btn btn-outline-primary  mx-2">Login</a>
                <a href="{% url 'signup'%}" class=" btn btn-bg mx-2">Signup</a>
                {%endif%}
            </div>
        </div>
    </nav>


    <div class="container my-5">
        <nav aria-label="breadcrumb" class="my-4">
            <ol class="breadcrumb bg-dark text-white py-3 fs-5 new-shadow">
            {% block breadcrump %}
            <li class="breadcrumb-item active" aria-current="page">Boards</li>
            {% endblock %}
            </ol>
        </nav>
        {%block content%}
        content
        {%endblock%}
    </div>
    {%endblock%}


    <script src="{% static 'js/jquery-3.7.1.min.js'%}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js'%}"></script>
</body>

</html>

templates/change_password.html
{% extends 'base.html' %}

{% block title%}
Change Password
{%endblock%}

{% block breadcrump%}
<li class="breadcrumb-item active">Change Password</li>
{%endblock%}

{% block content%}

<form method="post" class="form-control bg-light new-shadow-s p-4 " novalidate>

    {% csrf_token %}

    {% include 'includes/form.html'%}

    <br>
    <button type="submit" class="btn btn-success my-3 px-5">Change Password</button>


</form>

{%endblock%}

templates/change_password_done.html
{% extends 'base.html' %}

{% block title%}
Change Password succefull
{%endblock%}

{% block breadcrump%}
<li class="breadcrumb-item "><a href="{%url 'change_password'%}">Change Password</a></li>
<li class="breadcrumb-item active">Success</li>
{%endblock%}

{% block content%}

<div class="alert alert-success" role="alert">

    Your password has been changed :)
    
</div>
<a class="btn btn-secondary" href="{% url 'home' %}">Return to home</a>

{%endblock%}

templates/home.html
{% extends 'base.html' %}

{% block title%}
Boards
{%endblock%}

{% block breadcrump %}
<li class="breadcrumb-item active">Boards</li>
{%endblock%}


{% block content %}
<table class="table board-table new-shadow-s p-4 ">
    <thead class="table-dark fs-5">
        <th>Board</th>
        <th>Posts</th>
        <th>Topic</th>
        <th>Last Post</th>
    </thead>
    <tbody>
        {%for board in boards%}
        <tr>
            <td><a href="{% url 'board_topics' board.id %}">{{board.name}}</a>
                <small class="d-block text-muted">{{board.description}}</small>
            </td>
            <td>{{board.name}}</td>
            <td>{{board.name}}</td>
            <td>{{board.name}}</td>
        </tr>
        {%endfor%}
    </tbody>
</table>

{%endblock%}

templates/includes/form.html
{% load widget_tweaks %}


{% if form.non_field_errors%}

<div class="alert alert-danger">

    {% for error in form.non_field_errors %}
        <p {% if forloop.last %} class="mb-0" {%endif%}>{{error}}</p>
    {%endfor%}

</div>

{%endif%}

{% for field in form %}
<div class="mt-3 ">
    {{field.label_tag}}

    {% if form.is_bound %}
        {%if field.errors%}
        {% render_field field class="form-control is-invalid" %}
            {%for error in field.errors%}
            <div class="invalid-feedback">{{error}}</div>
            {%endfor%}
        {%else%}
        {% render_field field class="form-control is-valid" %}    
        {%endif%}
    
    {%else%}
    {% render_field field class="form-control" %}
    
    {%endif%}

</div>

{% if field.help_text %}
<small class="form-text text-muted">
    {{field.help_text}}
</small>
{%endif%}
{%endfor%}

templates/login.html
{% extends 'base.html' %}
{% block title%}
Sign up
{%endblock%}





{% block body %}
<div class="container d-flex justify-content-center align-items-center mt-5">
    <div class="w-50 p-5 new-shadow-s  ">
        <h1 class="text-center">Log in</h1>

        <form method="post" novalidate>

            {%csrf_token%}
            <input type="hidden" name="next" value="{{next}}">
            {% include 'includes/form.html' %}

            <button type="submit" class="btn btn-dark w-100 mt-3">Log in</button>

        </form>
        <div class="card-footer text-muted text-center mt-3">
            Create new account <a class="text-dark" href="{% url 'signup'%}">Sign up</a>
        </div>
    </div>
    
    
</div>

{%endblock%}

templates/new_topic.html
{% extends 'base.html' %}

{% block title%}
New Topic
{%endblock%}

{% block breadcrump%}

<li class="breadcrumb-item"><a href="{% url 'home' %}"> Boards</a></li>
<li class="breadcrumb-item"><a href="{% url 'board_topics' board.id%}">{{board.name}}</a></li>
<li class="breadcrumb-item active">New Topic</li>

{%endblock%}

{% block content%}

<form method="post" class="form-control bg-light new-shadow-s p-4 ">

    {% csrf_token %}


    <label for="id_subject" class="form-label my-3">Subject</label>
    <input class="form-control" type="text" name="subject" id="id_subject" required>

    <label class="form-label my-3" for="message">Message</label>
    <textarea class="form-control" name="message" id="id_message" rows="5" required></textarea>
    <button type="submit" class="btn btn-success my-3 px-5">Add</button>


</form>

{%endblock%}

templates/reply_topic.html
{% extends 'base.html' %}
{% load static %}
{% block title%}
{{topic.subject}}
{%endblock%}

{% block breadcrump%}
<li class="breadcrumb-item"><a href="{% url 'home' %}"> Boards</a></li>
<li class="breadcrumb-item"><a href="{% url 'board_topics' topic.board.pk %}">{{topic.board.name}}</a></li>
<li class="breadcrumb-item">{{topic.subject}}</li>
<li class="breadcrumb-item active">Post reply</li>
{%endblock%}

{% block content%}


<form method="post" class="mb-4">

    {% csrf_token%}

    {% include 'includes/form.html'%}
    <button type="submit" class="btn btn-primary my-3">Post a reply</button>
</form>


{%for post in topic.posts.all %}
<div class="new-shadow-s p-4 my-4">


    <div class="row align-items-center">

        <div class="image col-1 text-center">
            <img src="{% static 'imgs/user.png' %}" alt="{{post.created_by.username}}" class="w-100">
            <small class="fw-bold">{{post.created_by.username}}</small>
        </div>
        <div class="col-10">
            <p>{{post.message}}</p>
            <p>{{post.created_dt}}</p>
            {%if post.created_by == user%}
            <a href="#" class="btn btn-bg ">Edit</a>
            {%endif%}
        </div>
    </div>


</div>
    {%endfor%}


{%endblock%}

templates/signup.html
{% extends 'base.html' %}

{% block title%}
Sign up
{%endblock%}





{% block body %}
<div class="container d-flex justify-content-center align-items-center mt-5">
    <div class="w-50 p-5 new-shadow-s  ">
        <h1 class="text-center">Sign Up</h1>

        <form method="post" novalidate>

            {%csrf_token%}
            {{form.as_p}}
            <button type="submit" class="btn btn-dark w-100">Sign Up</button>

        </form>
        <div class="card-footer text-muted text-center mt-3">
            Already have account? <a class="text-dark" href="{% url 'login' %}">Log in</a>
        </div>
    </div>
    
    
</div>

{%endblock%}

templates/topic_posts.html
{% extends 'base.html' %}
{% load static %}
{% block title%}
{{topic.subject}}
{%endblock%}

{% block breadcrump%}
<li class="breadcrumb-item"><a href="{% url 'home' %}"> Boards</a></li>
<li class="breadcrumb-item"><a href="{% url 'board_topics' topic.board.pk %}">{{topic.board.name}}</a></li>
<li class="breadcrumb-item active">{{topic.subject}}</li>
{%endblock%}

{% block content%}

<a class="btn btn-bg my-3" href="{% url 'reply_topic' topic.board.pk topic.pk %}">Reply</a>


{%for post in topic.posts.all %}
<div class="new-shadow-s p-4 my-4">


    <div class="row align-items-center">

        <div class="image col-1 text-center">
            <img src="{% static 'imgs/user.png' %}" alt="{{post.created_by.username}}" class="w-100">
            <small class="fw-bold">{{post.created_by.username}}</small>
        </div>
        <div class="col-10">
            <p>{{post.message}}</p>
            <p>{{post.created_dt}}</p>
            {%if post.created_by == user%}
            <a href="#" class="btn btn-bg ">Edit</a>
            {%endif%}
        </div>
    </div>


</div>
    {%endfor%}


{%endblock%}

templates/topics.html
{% extends 'base.html' %}

{% block title%}
{{board.name}}
{%endblock%}

{% block breadcrump%}
<li class="breadcrumb-item"><a href="{% url 'home' %}"> Boards</a></li>
<li class="breadcrumb-item active">{{board.name}}</li>
{%endblock%}

{% block content%}

<div class="table new-shadow-s p-4">
    <table class="table">

        <thead class="table-dark fs-5">
            <th>Topics</th>
            <th>Created By</th>
            <th>Posts</th>
            <th>Views</th>
            <th>Created date</th>
        </thead>
        <tbody>
            {% for topic in board.topics.all %}
            
            <tr>
                <td><a href="{%url 'topic_posts' board.pk topic.pk %}">{{topic.subject}}</a></td>
                <td>{{topic.created_by}}</td>
                <td>0</td>
                <td>0</td>
                <td>{{topic.created_dt}}</td>
            </tr>
    
            {%endfor%}
        </tbody>
    
    
    
    
    </table>
</div>

<a class="btn btn-primary new-shadow" href="{% url 'new_topic' board.id %}">New Topic</a>
{%endblock%}